# URL do banco de dados
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/propostadb
      username: postgres
      password: 123
      driver-class-name: org.postgresql.Driver

# Configuracoes adicionais (opcional)
    jpa:
      hibernate.ddl-auto: create-drop
      show-sql: true
      properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

# RABBITMQ
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

rabbitmq-queue-proposta-pendente: proposta-pendente.ms-analise-credito